name: Automated API Tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Postman CLI
        run: |
          powershell.exe -NoProfile -InputFormat None -ExecutionPolicy AllSigned -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"

      - name: Login no Postman CLI
        run: |
          $env:POSTMAN_API_KEY="${{ secrets.POSTMAN_API_KEY }}"
          postman login --with-api-key $env:POSTMAN_API_KEY

      - name: Executar testes de API
        run: |
          postman collection run "32887155-ab8c059c-a445-4b93-bf41-06531bf45221" -e "32887155-62dbaf6a-6ee2-4a7f-82e6-fc5b3dd71dc5"
